#ifndef RECON_VERSION_H
#define RECON_VERSION_H

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "version.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
#define APPLICATION_VERSION_MAJOR       1
#define APPLICATION_VERSION_MINOR       0
#define APPLICATION_VERSION_PATCH       0
#define APPLICATION_VERSION_BUILD       11
#define APPLICATION_VERSION_TYPE        "-snapshot"
#define APPLICATION_VERSION_STRING      "1.0.0.11-snapshot"

#endif /* DUDE_VERSION_H */
