#ifndef RECON_VERSION_H
#define RECON_VERSION_H

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "version.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
#define APPLICATION_VERSION_MAJOR       @APPLICATION_VERSION_MAJOR@
#define APPLICATION_VERSION_MINOR       @APPLICATION_VERSION_MINOR@
#define APPLICATION_VERSION_PATCH       @APPLICATION_VERSION_PATCH@
#define APPLICATION_VERSION_BUILD       @APPLICATION_VERSION_BUILD@
#cmakedefine APPLICATION_VERSION_TYPE        "@APPLICATION_VERSION_TYPE@"
#cmakedefine APPLICATION_VERSION_STRING      "@APPLICATION_VERSION_STRING@"

#endif /* DUDE_VERSION_H */
